version: "3.8"

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    command: npm start
    working_dir: /app
  server:
    build:
      context: ./server
    ports:
      - "3002:3002"
    command: python index.py
    working_dir: /app